import { db } from '@/db';
import { leads } from '@/db/schema';

async function main() {
    const sampleLeads = [
        {
            userId: 'demo-user-1',
            name: 'Priya Sharma',
            phone: '+919876543210',
            email: 'priya.sharma@gmail.com',
            source: 'whatsapp',
            status: 'new',
            interest: 'Designer Kurtis',
            lastMessage: 'Hi, mujhe kurtis collection dekhna hai. Kya aap latest designs bhej sakte ho?',
            lastContacted: new Date('2024-03-15T10:30:00').toISOString(),
            notes: 'Interested in premium designer kurtis',
            createdAt: new Date('2024-03-15T10:30:00').toISOString(),
            updatedAt: new Date('2024-03-15T10:30:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Rajesh Kumar',
            phone: '+919123456789',
            email: null,
            source: 'whatsapp',
            status: 'contacted',
            interest: 'Mobile Accessories',
            lastMessage: 'Phone cases ke liye best price kya hai? Bulk order hai',
            lastContacted: new Date('2024-03-14T14:20:00').toISOString(),
            notes: 'Looking for bulk order of phone cases',
            createdAt: new Date('2024-03-14T09:15:00').toISOString(),
            updatedAt: new Date('2024-03-14T14:20:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Anjali Patel',
            phone: '+919988776655',
            email: 'anjali.patel@yahoo.com',
            source: 'website',
            status: 'qualified',
            interest: 'Banarasi Sarees',
            lastMessage: 'Wedding ke liye pure silk sarees chahiye. Budget 5000-8000',
            lastContacted: new Date('2024-03-13T16:45:00').toISOString(),
            notes: 'High-value customer, wedding shopping',
            createdAt: new Date('2024-03-13T11:20:00').toISOString(),
            updatedAt: new Date('2024-03-13T16:45:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Vikram Singh',
            phone: '+919876512345',
            email: null,
            source: 'whatsapp',
            status: 'converted',
            interest: 'Leather Handbags',
            lastMessage: 'Order confirm kar diya. Payment details bhej do',
            lastContacted: new Date('2024-03-12T18:30:00').toISOString(),
            notes: 'Purchased premium leather handbag - Rs 4500',
            createdAt: new Date('2024-03-10T10:00:00').toISOString(),
            updatedAt: new Date('2024-03-12T18:30:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Sneha Reddy',
            phone: '+919445566778',
            email: 'sneha.reddy@outlook.com',
            source: 'referral',
            status: 'new',
            interest: 'Traditional Jewelry',
            lastMessage: 'Meera ne refer kiya. Oxidised jewellery collection hai?',
            lastContacted: new Date('2024-03-15T09:15:00').toISOString(),
            notes: 'Referred by existing customer Meera',
            createdAt: new Date('2024-03-15T09:15:00').toISOString(),
            updatedAt: new Date('2024-03-15T09:15:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Arjun Malhotra',
            phone: '+919812345678',
            email: null,
            source: 'whatsapp',
            status: 'contacted',
            interest: 'Sports Shoes',
            lastMessage: 'Running shoes available hai? Size 10 chahiye',
            lastContacted: new Date('2024-03-14T11:40:00').toISOString(),
            notes: 'Looking for branded sports shoes',
            createdAt: new Date('2024-03-14T11:40:00').toISOString(),
            updatedAt: new Date('2024-03-14T11:40:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Kavya Iyer',
            phone: '+919667788990',
            email: 'kavya.iyer@gmail.com',
            source: 'website',
            status: 'qualified',
            interest: 'Home Decor',
            lastMessage: 'Wall hangings aur cushion covers ka collection dikhao',
            lastContacted: new Date('2024-03-13T15:20:00').toISOString(),
            notes: 'Interior designer, potential bulk orders',
            createdAt: new Date('2024-03-13T13:10:00').toISOString(),
            updatedAt: new Date('2024-03-13T15:20:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Rohit Gupta',
            phone: '+919334455667',
            email: null,
            source: 'whatsapp',
            status: 'lost',
            interest: 'Watches',
            lastMessage: 'Price bahut zyada hai. Discount milega?',
            lastContacted: new Date('2024-03-11T12:00:00').toISOString(),
            notes: 'Price sensitive, moved to competitor',
            createdAt: new Date('2024-03-10T14:30:00').toISOString(),
            updatedAt: new Date('2024-03-11T12:00:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Deepika Nair',
            phone: '+919223344556',
            email: 'deepika.nair@hotmail.com',
            source: 'whatsapp',
            status: 'converted',
            interest: 'Cotton Kurtis',
            lastMessage: 'Order delivered. Bahut achhe hain! Next order jaldi karungi',
            lastContacted: new Date('2024-03-12T17:00:00').toISOString(),
            notes: 'Repeat customer, very satisfied',
            createdAt: new Date('2024-03-08T10:20:00').toISOString(),
            updatedAt: new Date('2024-03-12T17:00:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Amit Verma',
            phone: '+919556677889',
            email: null,
            source: 'website',
            status: 'new',
            interest: 'Formal Shirts',
            lastMessage: 'Office wear ke liye formal shirts chahiye. Size chart bhejo',
            lastContacted: new Date('2024-03-15T11:45:00').toISOString(),
            notes: 'Corporate professional, needs formal wear',
            createdAt: new Date('2024-03-15T11:45:00').toISOString(),
            updatedAt: new Date('2024-03-15T11:45:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Pooja Kapoor',
            phone: '+919778899001',
            email: 'pooja.kapoor@gmail.com',
            source: 'whatsapp',
            status: 'contacted',
            interest: 'Kids Wear',
            lastMessage: 'Bachcho ke liye summer collection hai? 2-5 years age group',
            lastContacted: new Date('2024-03-14T10:30:00').toISOString(),
            notes: 'Mother of two, regular customer potential',
            createdAt: new Date('2024-03-14T10:30:00').toISOString(),
            updatedAt: new Date('2024-03-14T10:30:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Sanjay Mehta',
            phone: '+919889900112',
            email: null,
            source: 'whatsapp',
            status: 'qualified',
            interest: 'Electronic Gadgets',
            lastMessage: 'Bluetooth speakers ka range kya hai? Warranty kitne saal ki?',
            lastContacted: new Date('2024-03-13T14:15:00').toISOString(),
            notes: 'Tech enthusiast, interested in latest gadgets',
            createdAt: new Date('2024-03-13T09:00:00').toISOString(),
            updatedAt: new Date('2024-03-13T14:15:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Neha Desai',
            phone: '+919990011223',
            email: 'neha.desai@yahoo.com',
            source: 'referral',
            status: 'converted',
            interest: 'Cosmetics',
            lastMessage: 'Makeup kit received. Quality bahut achhi hai. Thank you!',
            lastContacted: new Date('2024-03-12T16:20:00').toISOString(),
            notes: 'Beauty blogger, good for product reviews',
            createdAt: new Date('2024-03-09T11:30:00').toISOString(),
            updatedAt: new Date('2024-03-12T16:20:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Karan Chopra',
            phone: '+919001122334',
            email: null,
            source: 'whatsapp',
            status: 'new',
            interest: 'Gym Equipment',
            lastMessage: 'Home gym setup ke liye equipment chahiye. Price list bhejo',
            lastContacted: new Date('2024-03-15T08:30:00').toISOString(),
            notes: 'Fitness enthusiast, potential high-value sale',
            createdAt: new Date('2024-03-15T08:30:00').toISOString(),
            updatedAt: new Date('2024-03-15T08:30:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Ritu Bansal',
            phone: '+919112233445',
            email: 'ritu.bansal@gmail.com',
            source: 'website',
            status: 'contacted',
            interest: 'Party Wear Sarees',
            lastMessage: 'Function hai next month. Designer sarees dikhao 10k budget mein',
            lastContacted: new Date('2024-03-14T13:50:00').toISOString(),
            notes: 'Looking for premium party wear',
            createdAt: new Date('2024-03-14T13:50:00').toISOString(),
            updatedAt: new Date('2024-03-14T13:50:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Manish Joshi',
            phone: '+919223344556',
            email: null,
            source: 'whatsapp',
            status: 'lost',
            interest: 'Laptops',
            lastMessage: 'Delivery charges bahut zyada hain. Cancel kardo',
            lastContacted: new Date('2024-03-11T15:30:00').toISOString(),
            notes: 'Lost due to high delivery charges',
            createdAt: new Date('2024-03-10T16:00:00').toISOString(),
            updatedAt: new Date('2024-03-11T15:30:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Divya Pillai',
            phone: '+919334455667',
            email: 'divya.pillai@outlook.com',
            source: 'whatsapp',
            status: 'qualified',
            interest: 'Handmade Crafts',
            lastMessage: 'Diwali gift items chahiye. Bulk order hoga',
            lastContacted: new Date('2024-03-13T12:00:00').toISOString(),
            notes: 'Corporate gifting opportunity',
            createdAt: new Date('2024-03-13T10:15:00').toISOString(),
            updatedAt: new Date('2024-03-13T12:00:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Aditya Rao',
            phone: '+919445566778',
            email: null,
            source: 'website',
            status: 'new',
            interest: 'Smart Watches',
            lastMessage: 'Fitness tracking wala watch chahiye. Latest model hai?',
            lastContacted: new Date('2024-03-15T12:20:00').toISOString(),
            notes: 'Tech-savvy customer',
            createdAt: new Date('2024-03-15T12:20:00').toISOString(),
            updatedAt: new Date('2024-03-15T12:20:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Swati Agarwal',
            phone: '+919556677889',
            email: 'swati.agarwal@gmail.com',
            source: 'whatsapp',
            status: 'converted',
            interest: 'Ethnic Wear',
            lastMessage: 'Suit set perfect hai! Next collection aane par batana',
            lastContacted: new Date('2024-03-12T14:40:00').toISOString(),
            notes: 'Loyal customer, loves ethnic wear',
            createdAt: new Date('2024-03-09T09:00:00').toISOString(),
            updatedAt: new Date('2024-03-12T14:40:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Rahul Saxena',
            phone: '+919667788990',
            email: null,
            source: 'whatsapp',
            status: 'contacted',
            interest: 'Books',
            lastMessage: 'Self-help aur business books hai? List share karo',
            lastContacted: new Date('2024-03-14T15:10:00').toISOString(),
            notes: 'Avid reader, interested in multiple genres',
            createdAt: new Date('2024-03-14T15:10:00').toISOString(),
            updatedAt: new Date('2024-03-14T15:10:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Meera Khanna',
            phone: '+919778899001',
            email: 'meera.khanna@yahoo.com',
            source: 'referral',
            status: 'qualified',
            interest: 'Organic Products',
            lastMessage: 'Chemical-free skincare products available hain? Pure organic chahiye',
            lastContacted: new Date('2024-03-13T11:30:00').toISOString(),
            notes: 'Health conscious, premium segment customer',
            createdAt: new Date('2024-03-13T10:00:00').toISOString(),
            updatedAt: new Date('2024-03-13T11:30:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Nikhil Bhatia',
            phone: '+919889900112',
            email: null,
            source: 'whatsapp',
            status: 'new',
            interest: 'Gaming Accessories',
            lastMessage: 'Gaming mouse aur keyboard ka combo hai? RGB lighting wala',
            lastContacted: new Date('2024-03-15T13:00:00').toISOString(),
            notes: 'Gamer, interested in premium accessories',
            createdAt: new Date('2024-03-15T13:00:00').toISOString(),
            updatedAt: new Date('2024-03-15T13:00:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Shreya Menon',
            phone: '+919990011223',
            email: 'shreya.menon@gmail.com',
            source: 'website',
            status: 'contacted',
            interest: 'Yoga Products',
            lastMessage: 'Yoga mats aur accessories chahiye. Eco-friendly material ho to better',
            lastContacted: new Date('2024-03-14T09:45:00').toISOString(),
            notes: 'Yoga instructor, potential for bulk orders',
            createdAt: new Date('2024-03-14T09:45:00').toISOString(),
            updatedAt: new Date('2024-03-14T09:45:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Varun Sinha',
            phone: '+919001122334',
            email: null,
            source: 'whatsapp',
            status: 'converted',
            interest: 'Travel Bags',
            lastMessage: 'Luggage bag delivered. Quality ekdum mast hai. Recommend karunga',
            lastContacted: new Date('2024-03-12T15:20:00').toISOString(),
            notes: 'Frequent traveler, satisfied with purchase',
            createdAt: new Date('2024-03-08T11:00:00').toISOString(),
            updatedAt: new Date('2024-03-12T15:20:00').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Tanvi Kulkarni',
            phone: '+919112233445',
            email: 'tanvi.kulkarni@outlook.com',
            source: 'whatsapp',
            status: 'qualified',
            interest: 'Home Appliances',
            lastMessage: 'Kitchen appliances ka range dikhao. New house setup hai',
            lastContacted: new Date('2024-03-13T16:30:00').toISOString(),
            notes: 'New home setup, high-value potential',
            createdAt: new Date('2024-03-13T14:00:00').toISOString(),
            updatedAt: new Date('2024-03-13T16:30:00').toISOString(),
        }
    ];

    await db.insert(leads).values(sampleLeads);
    
    console.log('✅ Leads seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});