import { db } from '@/db';
import { orders } from '@/db/schema';

async function main() {
    const sampleOrders = [
        // Day 1 (30 days ago) - 2 orders
        {
            userId: 'demo-user-1',
            leadId: 1,
            productId: 1,
            productName: "Women's Cotton Printed Kurti",
            quantity: 2,
            unitPrice: 699,
            totalAmount: 1398,
            status: 'completed',
            orderDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Priya Sharma',
            customerPhone: '+919876543210',
            createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 7,
            productName: 'Tempered Glass Screen Guard',
            quantity: 3,
            unitPrice: 199,
            totalAmount: 597,
            status: 'completed',
            orderDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Rahul Kumar',
            customerPhone: '+919123456780',
            createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 2 (29 days ago) - 3 orders
        {
            userId: 'demo-user-1',
            leadId: 2,
            productId: 8,
            productName: 'Fast Charging Type-C Cable',
            quantity: 4,
            unitPrice: 249,
            totalAmount: 996,
            status: 'completed',
            orderDate: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Amit Singh',
            customerPhone: '+919234567891',
            createdAt: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 3,
            productId: 3,
            productName: "Women's Rayon Palazzo Pants",
            quantity: 1,
            unitPrice: 449,
            totalAmount: 449,
            status: 'completed',
            orderDate: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Anjali Desai',
            customerPhone: '+919345678902',
            createdAt: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 11,
            productName: 'Stainless Steel Water Bottle',
            quantity: 2,
            unitPrice: 399,
            totalAmount: 798,
            status: 'completed',
            orderDate: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Vikram Patel',
            customerPhone: '+919456789013',
            createdAt: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 3 (28 days ago) - 2 orders
        {
            userId: 'demo-user-1',
            leadId: 4,
            productId: 14,
            productName: 'Genuine Leather Wallet',
            quantity: 1,
            unitPrice: 549,
            totalAmount: 549,
            status: 'completed',
            orderDate: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Sanjay Reddy',
            customerPhone: '+919567890124',
            createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 5,
            productId: 9,
            productName: 'TWS Wireless Earbuds',
            quantity: 1,
            unitPrice: 1299,
            totalAmount: 1299,
            status: 'cancelled',
            orderDate: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Neha Kapoor',
            customerPhone: '+919678901235',
            createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 4 (27 days ago) - 3 orders
        {
            userId: 'demo-user-1',
            leadId: 6,
            productId: 2,
            productName: 'Designer Anarkali Suit Set',
            quantity: 1,
            unitPrice: 1599,
            totalAmount: 1599,
            status: 'completed',
            orderDate: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Kavya Iyer',
            customerPhone: '+919789012346',
            createdAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 7,
            productName: 'Tempered Glass Screen Guard',
            quantity: 5,
            unitPrice: 199,
            totalAmount: 995,
            status: 'completed',
            orderDate: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Arjun Mehta',
            customerPhone: '+919890123457',
            createdAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 7,
            productId: 13,
            productName: 'LED Desk Lamp',
            quantity: 1,
            unitPrice: 699,
            totalAmount: 699,
            status: 'completed',
            orderDate: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Pooja Kulkarni',
            customerPhone: '+919901234568',
            createdAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 5 (26 days ago) - 2 orders
        {
            userId: 'demo-user-1',
            leadId: 8,
            productId: 10,
            productName: '20000mAh Power Bank',
            quantity: 1,
            unitPrice: 999,
            totalAmount: 999,
            status: 'completed',
            orderDate: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Rajesh Gupta',
            customerPhone: '+919012345679',
            createdAt: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 1,
            productName: "Women's Cotton Printed Kurti",
            quantity: 1,
            unitPrice: 699,
            totalAmount: 699,
            status: 'refunded',
            orderDate: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Ritu Agarwal',
            customerPhone: '+919123456790',
            createdAt: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 6 (25 days ago) - Weekend - 4 orders
        {
            userId: 'demo-user-1',
            leadId: 9,
            productId: 6,
            productName: 'Ethnic Printed Kurti with Pants',
            quantity: 2,
            unitPrice: 799,
            totalAmount: 1598,
            status: 'completed',
            orderDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Divya Nair',
            customerPhone: '+919234567801',
            createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 10,
            productId: 8,
            productName: 'Fast Charging Type-C Cable',
            quantity: 3,
            unitPrice: 249,
            totalAmount: 747,
            status: 'completed',
            orderDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Nikhil Joshi',
            customerPhone: '+919345678912',
            createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 15,
            productName: 'Designer Handbag',
            quantity: 1,
            unitPrice: 1099,
            totalAmount: 1099,
            status: 'completed',
            orderDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Sneha Chopra',
            customerPhone: '+919456789023',
            createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 11,
            productId: 16,
            productName: 'Polarized Sunglasses',
            quantity: 1,
            unitPrice: 649,
            totalAmount: 649,
            status: 'completed',
            orderDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Varun Malhotra',
            customerPhone: '+919567890134',
            createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 7 (24 days ago) - Weekend - 5 orders
        {
            userId: 'demo-user-1',
            leadId: 12,
            productId: 4,
            productName: 'Pure Silk Banarasi Saree',
            quantity: 1,
            unitPrice: 3299,
            totalAmount: 3299,
            status: 'completed',
            orderDate: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Meera Khanna',
            customerPhone: '+919678901245',
            createdAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 13,
            productId: 7,
            productName: 'Tempered Glass Screen Guard',
            quantity: 2,
            unitPrice: 199,
            totalAmount: 398,
            status: 'completed',
            orderDate: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Karan Verma',
            customerPhone: '+919789012356',
            createdAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 5,
            productName: "Men's Cotton Kurta Pajama Set",
            quantity: 1,
            unitPrice: 999,
            totalAmount: 999,
            status: 'completed',
            orderDate: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Rahul Sharma',
            customerPhone: '+919890123467',
            createdAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 14,
            productId: 11,
            productName: 'Stainless Steel Water Bottle',
            quantity: 3,
            unitPrice: 399,
            totalAmount: 1197,
            status: 'cancelled',
            orderDate: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Priya Verma',
            customerPhone: '+919901234578',
            createdAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 15,
            productId: 1,
            productName: "Women's Cotton Printed Kurti",
            quantity: 2,
            unitPrice: 699,
            totalAmount: 1398,
            status: 'completed',
            orderDate: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Anjali Desai',
            customerPhone: '+919345678902',
            createdAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 8 (23 days ago) - 2 orders
        {
            userId: 'demo-user-1',
            leadId: 16,
            productId: 12,
            productName: 'Non-Stick Cookware Set',
            quantity: 1,
            unitPrice: 1899,
            totalAmount: 1899,
            status: 'completed',
            orderDate: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Sanjay Patel',
            customerPhone: '+919012345689',
            createdAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 8,
            productName: 'Fast Charging Type-C Cable',
            quantity: 6,
            unitPrice: 249,
            totalAmount: 1494,
            status: 'completed',
            orderDate: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Vikram Singh',
            customerPhone: '+919123456700',
            createdAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 9 (22 days ago) - 3 orders
        {
            userId: 'demo-user-1',
            leadId: 17,
            productId: 3,
            productName: "Women's Rayon Palazzo Pants",
            quantity: 2,
            unitPrice: 449,
            totalAmount: 898,
            status: 'completed',
            orderDate: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Kavya Reddy',
            customerPhone: '+919234567811',
            createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 18,
            productId: 9,
            productName: 'TWS Wireless Earbuds',
            quantity: 1,
            unitPrice: 1299,
            totalAmount: 1299,
            status: 'completed',
            orderDate: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Amit Kumar',
            customerPhone: '+919123456780',
            createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 14,
            productName: 'Genuine Leather Wallet',
            quantity: 2,
            unitPrice: 549,
            totalAmount: 1098,
            status: 'completed',
            orderDate: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Arjun Reddy',
            customerPhone: '+919345678922',
            createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 10 (21 days ago) - 2 orders
        {
            userId: 'demo-user-1',
            leadId: 19,
            productId: 10,
            productName: '20000mAh Power Bank',
            quantity: 1,
            unitPrice: 999,
            totalAmount: 999,
            status: 'refunded',
            orderDate: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: null,
            customerName: 'Neha Kapoor',
            customerPhone: '+919678901235',
            createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 20,
            productId: 6,
            productName: 'Ethnic Printed Kurti with Pants',
            quantity: 1,
            unitPrice: 799,
            totalAmount: 799,
            status: 'completed',
            orderDate: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Pooja Kulkarni',
            customerPhone: '+919901234568',
            createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 11 (20 days ago) - 3 orders
        {
            userId: 'demo-user-1',
            leadId: 21,
            productId: 1,
            productName: "Women's Cotton Printed Kurti",
            quantity: 3,
            unitPrice: 699,
            totalAmount: 2097,
            status: 'completed',
            orderDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Ritu Agarwal',
            customerPhone: '+919123456790',
            createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 7,
            productName: 'Tempered Glass Screen Guard',
            quantity: 4,
            unitPrice: 199,
            totalAmount: 796,
            status: 'completed',
            orderDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Rajesh Gupta',
            customerPhone: '+919012345679',
            createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 22,
            productId: 13,
            productName: 'LED Desk Lamp',
            quantity: 1,
            unitPrice: 699,
            totalAmount: 699,
            status: 'cancelled',
            orderDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Divya Nair',
            customerPhone: '+919234567801',
            createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 12 (19 days ago) - 2 orders
        {
            userId: 'demo-user-1',
            leadId: 23,
            productId: 2,
            productName: 'Designer Anarkali Suit Set',
            quantity: 1,
            unitPrice: 1599,
            totalAmount: 1599,
            status: 'completed',
            orderDate: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Sneha Chopra',
            customerPhone: '+919456789023',
            createdAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 8,
            productName: 'Fast Charging Type-C Cable',
            quantity: 2,
            unitPrice: 249,
            totalAmount: 498,
            status: 'completed',
            orderDate: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Nikhil Joshi',
            customerPhone: '+919345678912',
            createdAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 13 (18 days ago) - Weekend - 5 orders
        {
            userId: 'demo-user-1',
            leadId: 24,
            productId: 11,
            productName: 'Stainless Steel Water Bottle',
            quantity: 2,
            unitPrice: 399,
            totalAmount: 798,
            status: 'completed',
            orderDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Varun Malhotra',
            customerPhone: '+919567890134',
            createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 25,
            productId: 15,
            productName: 'Designer Handbag',
            quantity: 1,
            unitPrice: 1099,
            totalAmount: 1099,
            status: 'completed',
            orderDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Meera Khanna',
            customerPhone: '+919678901245',
            createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 7,
            productName: 'Tempered Glass Screen Guard',
            quantity: 5,
            unitPrice: 199,
            totalAmount: 995,
            status: 'completed',
            orderDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Karan Verma',
            customerPhone: '+919789012356',
            createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 1,
            productId: 3,
            productName: "Women's Rayon Palazzo Pants",
            quantity: 1,
            unitPrice: 449,
            totalAmount: 449,
            status: 'completed',
            orderDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Priya Sharma',
            customerPhone: '+919876543210',
            createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 2,
            productId: 16,
            productName: 'Polarized Sunglasses',
            quantity: 1,
            unitPrice: 649,
            totalAmount: 649,
            status: 'completed',
            orderDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Amit Singh',
            customerPhone: '+919234567891',
            createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 14 (17 days ago) - Weekend - 6 orders
        {
            userId: 'demo-user-1',
            leadId: 3,
            productId: 1,
            productName: "Women's Cotton Printed Kurti",
            quantity: 2,
            unitPrice: 699,
            totalAmount: 1398,
            status: 'completed',
            orderDate: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Anjali Desai',
            customerPhone: '+919345678902',
            createdAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 9,
            productName: 'TWS Wireless Earbuds',
            quantity: 1,
            unitPrice: 1299,
            totalAmount: 1299,
            status: 'completed',
            orderDate: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Rahul Sharma',
            customerPhone: '+919890123467',
            createdAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 4,
            productId: 10,
            productName: '20000mAh Power Bank',
            quantity: 2,
            unitPrice: 999,
            totalAmount: 1998,
            status: 'completed',
            orderDate: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Sanjay Reddy',
            customerPhone: '+919567890124',
            createdAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 5,
            productId: 5,
            productName: "Men's Cotton Kurta Pajama Set",
            quantity: 1,
            unitPrice: 999,
            totalAmount: 999,
            status: 'cancelled',
            orderDate: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Neha Kapoor',
            customerPhone: '+919678901235',
            createdAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 8,
            productName: 'Fast Charging Type-C Cable',
            quantity: 8,
            unitPrice: 249,
            totalAmount: 1992,
            status: 'completed',
            orderDate: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Vikram Patel',
            customerPhone: '+919456789013',
            createdAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 6,
            productId: 14,
            productName: 'Genuine Leather Wallet',
            quantity: 1,
            unitPrice: 549,
            totalAmount: 549,
            status: 'completed',
            orderDate: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Kavya Iyer',
            customerPhone: '+919789012346',
            createdAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 15 (16 days ago) - 3 orders
        {
            userId: 'demo-user-1',
            leadId: 7,
            productId: 6,
            productName: 'Ethnic Printed Kurti with Pants',
            quantity: 1,
            unitPrice: 799,
            totalAmount: 799,
            status: 'completed',
            orderDate: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Pooja Kulkarni',
            customerPhone: '+919901234568',
            createdAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 12,
            productName: 'Non-Stick Cookware Set',
            quantity: 1,
            unitPrice: 1899,
            totalAmount: 1899,
            status: 'completed',
            orderDate: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Arjun Mehta',
            customerPhone: '+919890123457',
            createdAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 8,
            productId: 7,
            productName: 'Tempered Glass Screen Guard',
            quantity: 3,
            unitPrice: 199,
            totalAmount: 597,
            status: 'refunded',
            orderDate: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: null,
            customerName: 'Rajesh Gupta',
            customerPhone: '+919012345679',
            createdAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 16 (15 days ago) - 3 orders
        {
            userId: 'demo-user-1',
            leadId: 9,
            productId: 2,
            productName: 'Designer Anarkali Suit Set',
            quantity: 1,
            unitPrice: 1599,
            totalAmount: 1599,
            status: 'completed',
            orderDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Divya Nair',
            customerPhone: '+919234567801',
            createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 10,
            productId: 13,
            productName: 'LED Desk Lamp',
            quantity: 2,
            unitPrice: 699,
            totalAmount: 1398,
            status: 'completed',
            orderDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Nikhil Joshi',
            customerPhone: '+919345678912',
            createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 11,
            productName: 'Stainless Steel Water Bottle',
            quantity: 1,
            unitPrice: 399,
            totalAmount: 399,
            status: 'completed',
            orderDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Ritu Agarwal',
            customerPhone: '+919123456790',
            createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 17 (14 days ago) - 2 orders
        {
            userId: 'demo-user-1',
            leadId: 11,
            productId: 1,
            productName: "Women's Cotton Printed Kurti",
            quantity: 1,
            unitPrice: 699,
            totalAmount: 699,
            status: 'completed',
            orderDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Varun Malhotra',
            customerPhone: '+919567890134',
            createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 12,
            productId: 8,
            productName: 'Fast Charging Type-C Cable',
            quantity: 2,
            unitPrice: 249,
            totalAmount: 498,
            status: 'cancelled',
            orderDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Meera Khanna',
            customerPhone: '+919678901245',
            createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 18 (13 days ago) - 3 orders
        {
            userId: 'demo-user-1',
            leadId: 13,
            productId: 4,
            productName: 'Pure Silk Banarasi Saree',
            quantity: 1,
            unitPrice: 3299,
            totalAmount: 3299,
            status: 'completed',
            orderDate: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Karan Verma',
            customerPhone: '+919789012356',
            createdAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 15,
            productName: 'Designer Handbag',
            quantity: 1,
            unitPrice: 1099,
            totalAmount: 1099,
            status: 'completed',
            orderDate: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Sneha Chopra',
            customerPhone: '+919456789023',
            createdAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 14,
            productId: 9,
            productName: 'TWS Wireless Earbuds',
            quantity: 1,
            unitPrice: 1299,
            totalAmount: 1299,
            status: 'completed',
            orderDate: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Priya Verma',
            customerPhone: '+919901234578',
            createdAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 19 (12 days ago) - 2 orders
        {
            userId: 'demo-user-1',
            leadId: 15,
            productId: 3,
            productName: "Women's Rayon Palazzo Pants",
            quantity: 2,
            unitPrice: 449,
            totalAmount: 898,
            status: 'completed',
            orderDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Anjali Desai',
            customerPhone: '+919345678902',
            createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 7,
            productName: 'Tempered Glass Screen Guard',
            quantity: 6,
            unitPrice: 199,
            totalAmount: 1194,
            status: 'completed',
            orderDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Rahul Sharma',
            customerPhone: '+919890123467',
            createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 20 (11 days ago) - Weekend - 5 orders
        {
            userId: 'demo-user-1',
            leadId: 16,
            productId: 10,
            productName: '20000mAh Power Bank',
            quantity: 1,
            unitPrice: 999,
            totalAmount: 999,
            status: 'completed',
            orderDate: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Sanjay Patel',
            customerPhone: '+919012345689',
            createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 17,
            productId: 6,
            productName: 'Ethnic Printed Kurti with Pants',
            quantity: 2,
            unitPrice: 799,
            totalAmount: 1598,
            status: 'completed',
            orderDate: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Kavya Reddy',
            customerPhone: '+919234567811',
            createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 16,
            productName: 'Polarized Sunglasses',
            quantity: 1,
            unitPrice: 649,
            totalAmount: 649,
            status: 'completed',
            orderDate: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Vikram Singh',
            customerPhone: '+919123456700',
            createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 18,
            productId: 1,
            productName: "Women's Cotton Printed Kurti",
            quantity: 2,
            unitPrice: 699,
            totalAmount: 1398,
            status: 'completed',
            orderDate: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Amit Kumar',
            customerPhone: '+919123456780',
            createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 19,
            productId: 8,
            productName: 'Fast Charging Type-C Cable',
            quantity: 5,
            unitPrice: 249,
            totalAmount: 1245,
            status: 'completed',
            orderDate: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Neha Kapoor',
            customerPhone: '+919678901235',
            createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 21 (10 days ago) - Weekend - 6 orders
        {
            userId: 'demo-user-1',
            leadId: 20,
            productId: 14,
            productName: 'Genuine Leather Wallet',
            quantity: 1,
            unitPrice: 549,
            totalAmount: 549,
            status: 'completed',
            orderDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Pooja Kulkarni',
            customerPhone: '+919901234568',
            createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 11,
            productName: 'Stainless Steel Water Bottle',
            quantity: 3,
            unitPrice: 399,
            totalAmount: 1197,
            status: 'completed',
            orderDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Arjun Reddy',
            customerPhone: '+919345678922',
            createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 21,
            productId: 2,
            productName: 'Designer Anarkali Suit Set',
            quantity: 1,
            unitPrice: 1599,
            totalAmount: 1599,
            status: 'refunded',
            orderDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Ritu Agarwal',
            customerPhone: '+919123456790',
            createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 22,
            productId: 13,
            productName: 'LED Desk Lamp',
            quantity: 1,
            unitPrice: 699,
            totalAmount: 699,
            status: 'completed',
            orderDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Divya Nair',
            customerPhone: '+919234567801',
            createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 7,
            productName: 'Tempered Glass Screen Guard',
            quantity: 4,
            unitPrice: 199,
            totalAmount: 796,
            status: 'completed',
            orderDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Rajesh Gupta',
            customerPhone: '+919012345679',
            createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 23,
            productId: 5,
            productName: "Men's Cotton Kurta Pajama Set",
            quantity: 1,
            unitPrice: 999,
            totalAmount: 999,
            status: 'completed',
            orderDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Sneha Chopra',
            customerPhone: '+919456789023',
            createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 22 (9 days ago) - 3 orders
        {
            userId: 'demo-user-1',
            leadId: 24,
            productId: 9,
            productName: 'TWS Wireless Earbuds',
            quantity: 1,
            unitPrice: 1299,
            totalAmount: 1299,
            status: 'completed',
            orderDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Varun Malhotra',
            customerPhone: '+919567890134',
            createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 25,
            productId: 12,
            productName: 'Non-Stick Cookware Set',
            quantity: 1,
            unitPrice: 1899,
            totalAmount: 1899,
            status: 'cancelled',
            orderDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Meera Khanna',
            customerPhone: '+919678901245',
            createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 3,
            productName: "Women's Rayon Palazzo Pants",
            quantity: 1,
            unitPrice: 449,
            totalAmount: 449,
            status: 'completed',
            orderDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Nikhil Joshi',
            customerPhone: '+919345678912',
            createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 23 (8 days ago) - 4 orders
        {
            userId: 'demo-user-1',
            leadId: 1,
            productId: 1,
            productName: "Women's Cotton Printed Kurti",
            quantity: 1,
            unitPrice: 699,
            totalAmount: 699,
            status: 'completed',
            orderDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Priya Sharma',
            customerPhone: '+919876543210',
            createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 2,
            productId: 15,
            productName: 'Designer Handbag',
            quantity: 1,
            unitPrice: 1099,
            totalAmount: 1099,
            status: 'completed',
            orderDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Amit Singh',
            customerPhone: '+919234567891',
            createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 8,
            productName: 'Fast Charging Type-C Cable',
            quantity: 3,
            unitPrice: 249,
            totalAmount: 747,
            status: 'completed',
            orderDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Karan Verma',
            customerPhone: '+919789012356',
            createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 3,
            productId: 10,
            productName: '20000mAh Power Bank',
            quantity: 1,
            unitPrice: 999,
            totalAmount: 999,
            status: 'completed',
            orderDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Anjali Desai',
            customerPhone: '+919345678902',
            createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Last 7 days - Day 24 (7 days ago) - 3 orders
        {
            userId: 'demo-user-1',
            leadId: 4,
            productId: 6,
            productName: 'Ethnic Printed Kurti with Pants',
            quantity: 1,
            unitPrice: 799,
            totalAmount: 799,
            status: 'completed',
            orderDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Sanjay Reddy',
            customerPhone: '+919567890124',
            createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 7,
            productName: 'Tempered Glass Screen Guard',
            quantity: 5,
            unitPrice: 199,
            totalAmount: 995,
            status: 'completed',
            orderDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Vikram Patel',
            customerPhone: '+919456789013',
            createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 5,
            productId: 16,
            productName: 'Polarized Sunglasses',
            quantity: 1,
            unitPrice: 649,
            totalAmount: 649,
            status: 'pending',
            orderDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Neha Kapoor',
            customerPhone: '+919678901235',
            createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 25 (6 days ago) - 3 orders
        {
            userId: 'demo-user-1',
            leadId: 6,
            productId: 2,
            productName: 'Designer Anarkali Suit Set',
            quantity: 1,
            unitPrice: 1599,
            totalAmount: 1599,
            status: 'pending',
            orderDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Kavya Iyer',
            customerPhone: '+919789012346',
            createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 7,
            productId: 11,
            productName: 'Stainless Steel Water Bottle',
            quantity: 2,
            unitPrice: 399,
            totalAmount: 798,
            status: 'completed',
            orderDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Pooja Kulkarni',
            customerPhone: '+919901234568',
            createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 9,
            productName: 'TWS Wireless Earbuds',
            quantity: 1,
            unitPrice: 1299,
            totalAmount: 1299,
            status: 'completed',
            orderDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Rahul Sharma',
            customerPhone: '+919890123467',
            createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 26 (5 days ago) - 3 orders
        {
            userId: 'demo-user-1',
            leadId: 8,
            productId: 1,
            productName: "Women's Cotton Printed Kurti",
            quantity: 2,
            unitPrice: 699,
            totalAmount: 1398,
            status: 'completed',
            orderDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Rajesh Gupta',
            customerPhone: '+919012345679',
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 9,
            productId: 8,
            productName: 'Fast Charging Type-C Cable',
            quantity: 4,
            unitPrice: 249,
            totalAmount: 996,
            status: 'pending',
            orderDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Divya Nair',
            customerPhone: '+919234567801',
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 14,
            productName: 'Genuine Leather Wallet',
            quantity: 1,
            unitPrice: 549,
            totalAmount: 549,
            status: 'completed',
            orderDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Arjun Mehta',
            customerPhone: '+919890123457',
            createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 27 (4 days ago) - Weekend - 4 orders
        {
            userId: 'demo-user-1',
            leadId: 10,
            productId: 4,
            productName: 'Pure Silk Banarasi Saree',
            quantity: 1,
            unitPrice: 3299,
            totalAmount: 3299,
            status: 'pending',
            orderDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Nikhil Joshi',
            customerPhone: '+919345678912',
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 11,
            productId: 13,
            productName: 'LED Desk Lamp',
            quantity: 1,
            unitPrice: 699,
            totalAmount: 699,
            status: 'pending',
            orderDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Varun Malhotra',
            customerPhone: '+919567890134',
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 7,
            productName: 'Tempered Glass Screen Guard',
            quantity: 3,
            unitPrice: 199,
            totalAmount: 597,
            status: 'completed',
            orderDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Ritu Agarwal',
            customerPhone: '+919123456790',
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 12,
            productId: 3,
            productName: "Women's Rayon Palazzo Pants",
            quantity: 2,
            unitPrice: 449,
            totalAmount: 898,
            status: 'pending',
            orderDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Meera Khanna',
            customerPhone: '+919678901245',
            createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 28 (3 days ago) - Weekend - 4 orders
        {
            userId: 'demo-user-1',
            leadId: 13,
            productId: 10,
            productName: '20000mAh Power Bank',
            quantity: 1,
            unitPrice: 999,
            totalAmount: 999,
            status: 'pending',
            orderDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Karan Verma',
            customerPhone: '+919789012356',
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 6,
            productName: 'Ethnic Printed Kurti with Pants',
            quantity: 1,
            unitPrice: 799,
            totalAmount: 799,
            status: 'pending',
            orderDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Sneha Chopra',
            customerPhone: '+919456789023',
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 14,
            productId: 15,
            productName: 'Designer Handbag',
            quantity: 1,
            unitPrice: 1099,
            totalAmount: 1099,
            status: 'completed',
            orderDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Priya Verma',
            customerPhone: '+919901234578',
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 15,
            productId: 8,
            productName: 'Fast Charging Type-C Cable',
            quantity: 7,
            unitPrice: 249,
            totalAmount: 1743,
            status: 'pending',
            orderDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Anjali Desai',
            customerPhone: '+919345678902',
            createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 29 (2 days ago) - 3 orders
        {
            userId: 'demo-user-1',
            leadId: 16,
            productId: 1,
            productName: "Women's Cotton Printed Kurti",
            quantity: 1,
            unitPrice: 699,
            totalAmount: 699,
            status: 'pending',
            orderDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Sanjay Patel',
            customerPhone: '+919012345689',
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 11,
            productName: 'Stainless Steel Water Bottle',
            quantity: 2,
            unitPrice: 399,
            totalAmount: 798,
            status: 'pending',
            orderDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Vikram Singh',
            customerPhone: '+919123456700',
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 17,
            productId: 9,
            productName: 'TWS Wireless Earbuds',
            quantity: 1,
            unitPrice: 1299,
            totalAmount: 1299,
            status: 'pending',
            orderDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'Card',
            customerName: 'Kavya Reddy',
            customerPhone: '+919234567811',
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Day 30 (1 day ago) - 3 orders
        {
            userId: 'demo-user-1',
            leadId: 18,
            productId: 2,
            productName: 'Designer Anarkali Suit Set',
            quantity: 1,
            unitPrice: 1599,
            totalAmount: 1599,
            status: 'pending',
            orderDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Amit Kumar',
            customerPhone: '+919123456780',
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 7,
            productName: 'Tempered Glass Screen Guard',
            quantity: 4,
            unitPrice: 199,
            totalAmount: 796,
            status: 'pending',
            orderDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'COD',
            customerName: 'Arjun Reddy',
            customerPhone: '+919345678922',
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: 19,
            productId: 16,
            productName: 'Polarized Sunglasses',
            quantity: 1,
            unitPrice: 649,
            totalAmount: 649,
            status: 'pending',
            orderDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            paymentMethod: 'UPI',
            customerName: 'Neha Kapoor',
            customerPhone: '+919678901235',
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        // Today - 2 orders
        {
            userId: 'demo-user-1',
            leadId: 20,
            productId: 5,
            productName: "Men's Cotton Kurta Pajama Set",
            quantity: 1,
            unitPrice: 999,
            totalAmount: 999,
            status: 'pending',
            orderDate: new Date().toISOString(),
            paymentMethod: 'COD',
            customerName: 'Pooja Kulkarni',
            customerPhone: '+919901234568',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            userId: 'demo-user-1',
            leadId: null,
            productId: 12,
            productName: 'Non-Stick Cookware Set',
            quantity: 1,
            unitPrice: 1899,
            totalAmount: 1899,
            status: 'pending',
            orderDate: new Date().toISOString(),
            paymentMethod: 'Card',
            customerName: 'Rahul Sharma',
            customerPhone: '+919890123467',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        }
    ];

    await db.insert(orders).values(sampleOrders);
    
    console.log('✅ Orders seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});