import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Indian Clothing (5-6 products)
        {
            userId: 'demo-user-1',
            name: 'Women\'s Cotton Printed Kurti',
            description: 'Elegant printed kurti in soft cotton fabric. Perfect for casual and semi-formal occasions. Features A-line cut and 3/4 sleeves.',
            price: 699,
            stock: 45,
            category: 'Indian Clothing',
            imageUrl: '/products/kurti-1.jpg',
            colors: JSON.stringify(['Blue', 'Pink', 'Green', 'Yellow']),
            sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL']),
            sku: 'KRT-001',
            status: 'active',
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Designer Anarkali Suit Set',
            description: 'Beautiful designer Anarkali suit with dupatta. Premium quality georgette fabric with intricate embroidery work.',
            price: 1599,
            stock: 28,
            category: 'Indian Clothing',
            imageUrl: '/products/anarkali-1.jpg',
            colors: JSON.stringify(['Maroon', 'Navy Blue', 'Royal Blue', 'Black']),
            sizes: JSON.stringify(['M', 'L', 'XL', 'XXL']),
            sku: 'ANK-001',
            status: 'active',
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Women\'s Rayon Palazzo Pants',
            description: 'Comfortable palazzo pants in soft rayon fabric. Perfect for daily wear with kurti or tops.',
            price: 449,
            stock: 65,
            category: 'Indian Clothing',
            imageUrl: '/products/palazzo-1.jpg',
            colors: JSON.stringify(['Black', 'White', 'Navy', 'Grey', 'Brown']),
            sizes: JSON.stringify(['M', 'L', 'XL', 'XXL']),
            sku: 'PLZ-001',
            status: 'active',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Pure Silk Banarasi Saree',
            description: 'Authentic Banarasi silk saree with traditional zari work. Comes with matching blouse piece. Perfect for weddings and festivals.',
            price: 3299,
            stock: 12,
            category: 'Indian Clothing',
            imageUrl: '/products/saree-1.jpg',
            colors: JSON.stringify(['Red', 'Gold', 'Green', 'Purple']),
            sizes: JSON.stringify(['Free Size']),
            sku: 'SAR-001',
            status: 'active',
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Men\'s Cotton Kurta Pajama Set',
            description: 'Classic cotton kurta pajama set for men. Comfortable fit perfect for festivals and traditional occasions.',
            price: 999,
            stock: 35,
            category: 'Indian Clothing',
            imageUrl: '/products/kurta-men-1.jpg',
            colors: JSON.stringify(['White', 'Cream', 'Light Blue', 'Beige']),
            sizes: JSON.stringify(['M', 'L', 'XL', 'XXL']),
            sku: 'KRM-001',
            status: 'active',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Ethnic Printed Kurti with Pants',
            description: 'Stylish printed kurti with matching pants. Made from premium rayon fabric with beautiful ethnic prints.',
            price: 799,
            stock: 42,
            category: 'Indian Clothing',
            imageUrl: '/products/kurti-set-1.jpg',
            colors: JSON.stringify(['Multicolor', 'Blue Print', 'Red Print']),
            sizes: JSON.stringify(['S', 'M', 'L', 'XL', 'XXL']),
            sku: 'KRT-002',
            status: 'active',
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        
        // Mobile Accessories (3-4 products)
        {
            userId: 'demo-user-1',
            name: 'Tempered Glass Screen Guard',
            description: '9H hardness tempered glass screen protector. Edge-to-edge protection with oleophobic coating. Compatible with most smartphones.',
            price: 199,
            stock: 150,
            category: 'Mobile Accessories',
            imageUrl: '/products/screen-guard-1.jpg',
            colors: JSON.stringify(['Clear']),
            sizes: JSON.stringify(['Universal']),
            sku: 'SCR-001',
            status: 'active',
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Fast Charging Type-C Cable',
            description: 'Braided Type-C cable with fast charging support up to 65W. 1.5 meter length with reinforced connectors.',
            price: 249,
            stock: 200,
            category: 'Mobile Accessories',
            imageUrl: '/products/cable-1.jpg',
            colors: JSON.stringify(['Black', 'White', 'Blue', 'Red']),
            sizes: JSON.stringify(['1.5m']),
            sku: 'CAB-001',
            status: 'active',
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'TWS Wireless Earbuds',
            description: 'True wireless stereo earbuds with active noise cancellation. 30 hours total battery life with charging case. IPX5 water resistant.',
            price: 1299,
            stock: 55,
            category: 'Mobile Accessories',
            imageUrl: '/products/earbuds-1.jpg',
            colors: JSON.stringify(['Black', 'White', 'Blue']),
            sizes: JSON.stringify(['One Size']),
            sku: 'EAR-001',
            status: 'active',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: '20000mAh Power Bank',
            description: 'High capacity power bank with dual USB output and Type-C input. Fast charging support with LED display showing battery percentage.',
            price: 999,
            stock: 80,
            category: 'Mobile Accessories',
            imageUrl: '/products/powerbank-1.jpg',
            colors: JSON.stringify(['Black', 'White', 'Blue']),
            sizes: JSON.stringify(['20000mAh']),
            sku: 'PWR-001',
            status: 'active',
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        
        // Home & Kitchen (2-3 products)
        {
            userId: 'demo-user-1',
            name: 'Stainless Steel Water Bottle',
            description: 'Premium vacuum insulated water bottle. Keeps beverages hot for 12 hours and cold for 24 hours. BPA free and leak proof.',
            price: 399,
            stock: 120,
            category: 'Home & Kitchen',
            imageUrl: '/products/bottle-1.jpg',
            colors: JSON.stringify(['Silver', 'Black', 'Blue', 'Pink']),
            sizes: JSON.stringify(['500ml', '750ml', '1000ml']),
            sku: 'BTL-001',
            status: 'active',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Non-Stick Cookware Set',
            description: '5-piece non-stick cookware set including kadhai, frying pan, and saucepans. Aluminum body with 3-layer non-stick coating.',
            price: 1899,
            stock: 40,
            category: 'Home & Kitchen',
            imageUrl: '/products/cookware-1.jpg',
            colors: JSON.stringify(['Black', 'Red']),
            sizes: JSON.stringify(['5 Piece Set']),
            sku: 'CKW-001',
            status: 'active',
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'LED Desk Lamp with USB Port',
            description: 'Adjustable LED desk lamp with touch control and 3 color modes. Built-in USB charging port. Energy efficient with 50000 hours lifespan.',
            price: 699,
            stock: 75,
            category: 'Home & Kitchen',
            imageUrl: '/products/lamp-1.jpg',
            colors: JSON.stringify(['White', 'Black']),
            sizes: JSON.stringify(['Standard']),
            sku: 'LMP-001',
            status: 'active',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        
        // Fashion Accessories (2-3 products)
        {
            userId: 'demo-user-1',
            name: 'Genuine Leather Wallet',
            description: 'Premium quality genuine leather wallet with multiple card slots and cash compartment. RFID blocking for security.',
            price: 549,
            stock: 90,
            category: 'Fashion Accessories',
            imageUrl: '/products/wallet-1.jpg',
            colors: JSON.stringify(['Brown', 'Black', 'Tan']),
            sizes: JSON.stringify(['Standard']),
            sku: 'WLT-001',
            status: 'active',
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Designer Handbag for Women',
            description: 'Stylish handbag with adjustable strap. Multiple compartments including zipper pockets. Premium PU leather finish.',
            price: 1099,
            stock: 48,
            category: 'Fashion Accessories',
            imageUrl: '/products/handbag-1.jpg',
            colors: JSON.stringify(['Black', 'Brown', 'Beige', 'Red']),
            sizes: JSON.stringify(['Medium']),
            sku: 'HND-001',
            status: 'active',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            userId: 'demo-user-1',
            name: 'Polarized Sunglasses',
            description: 'UV400 protection polarized sunglasses. Reduces glare and eye strain. Durable frame with scratch-resistant lenses.',
            price: 649,
            stock: 65,
            category: 'Fashion Accessories',
            imageUrl: '/products/sunglasses-1.jpg',
            colors: JSON.stringify(['Black', 'Brown', 'Grey']),
            sizes: JSON.stringify(['Standard']),
            sku: 'SNG-001',
            status: 'active',
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});